#!/usr/bin/env bash

# =============================================================================
# Gaming Mode Setup Wizard
# Generates gaming-mode.conf for system-specific configuration
# Auto-detects GPUs, monitors, DRM devices, UWSM env, and Hyprland config
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh" || {
	echo "Failed to load utils.sh"
	exit 1
}

# =============================================================================
# SECTION 1: Requirements Check
# =============================================================================

fmtr::box_text "Gaming Mode Setup Wizard"
fmtr::info "Requirements: Arch Linux + Hyprland + UWSM + config.conf"
echo ""

# Verify Hyprland is running
if ! command -v hyprctl &>/dev/null || ! hyprctl monitors &>/dev/null 2>&1; then
	fmtr::error "Hyprland is not running. This script requires a Hyprland session."
	fmtr::info "Run this wizard from within a Hyprland session."
	exit 1
fi
fmtr::log "Hyprland: running"

# Verify UWSM is installed
if ! command -v uwsm &>/dev/null; then
	fmtr::error "UWSM not found. Install it: yay -S uwsm"
	exit 1
fi
fmtr::log "UWSM: installed"

# Verify config.conf exists (from module 03 VFIO setup)
if [[ ! -f "${SCRIPT_DIR}/config.conf" ]]; then
	fmtr::error "config.conf not found. Run module 4 (VFIO Setup) first."
	fmtr::info "config.conf is generated by the VFIO module and contains GPU PCI info."
	exit 1
fi

# Load GPU info from config.conf
source "${SCRIPT_DIR}/config.conf"
if [[ -z "$GPU_PCI_ADDR" ]]; then
	fmtr::error "GPU_PCI_ADDR not found in config.conf. Run VFIO setup first."
	exit 1
fi
fmtr::log "GPU from config.conf: $GPU_PCI_ADDR ($GPU_NAME)"

# =============================================================================
# SECTION 2: Detect GPU PCI Addresses
# =============================================================================

fmtr::info "Detecting GPU PCI addresses..."

# Auto-detect audio sibling (same PCI slot, function 1)
gpu_slot="${GPU_PCI_ADDR%.*}"
gpu_audio_pci="${GPU_AUDIO_PCI:-${gpu_slot}.1}"
if [[ -e "/sys/bus/pci/devices/${gpu_audio_pci}" ]]; then
	fmtr::log "GPU audio device: $gpu_audio_pci"
else
	fmtr::warn "No audio device found at $gpu_audio_pci"
	gpu_audio_pci=""
fi

# Detect original driver for audio device
gpu_audio_original_driver="snd_hda_intel"
if [[ -n "$gpu_audio_pci" ]]; then
	gpu_audio_original_driver=$(readlink "/sys/bus/pci/devices/${gpu_audio_pci}/driver" \
		2>/dev/null | xargs basename 2>/dev/null || echo "snd_hda_intel")
	fmtr::log "Audio device original driver: $gpu_audio_original_driver"
fi

# =============================================================================
# SECTION 3: Detect DRM Card Numbers (by PCI ID, NOT by card number)
# =============================================================================

fmtr::info "Detecting DRM card numbers by PCI ID..."

# Read dGPU vendor:device from sysfs
dgpu_vendor=$(cat "/sys/bus/pci/devices/${GPU_PCI_ADDR}/vendor" 2>/dev/null)
dgpu_vendor=${dgpu_vendor#0x}
dgpu_device=$(cat "/sys/bus/pci/devices/${GPU_PCI_ADDR}/device" 2>/dev/null)
dgpu_device=${dgpu_device#0x}
dgpu_pci_id="${dgpu_vendor}:${dgpu_device}"
fmtr::info "dGPU PCI ID: $dgpu_pci_id"

drm_dgpu=""
drm_igpu=""

for card in /sys/class/drm/card[0-9]*; do
	[[ -d "$card/device" ]] || continue
	# Skip render nodes and sub-devices
	[[ "$(basename "$card")" =~ ^card[0-9]+$ ]] || continue

	card_vendor=$(cat "$card/device/vendor" 2>/dev/null)
	card_vendor=${card_vendor#0x}
	card_device=$(cat "$card/device/device" 2>/dev/null)
	card_device=${card_device#0x}
	[[ -z "$card_vendor" || -z "$card_device" ]] && continue

	card_pci_id="${card_vendor}:${card_device}"
	card_name=$(basename "$card")

	fmtr::info "  Found $card_name: PCI ID $card_pci_id"

	if [[ "$card_pci_id" == "$dgpu_pci_id" ]]; then
		drm_dgpu="/dev/dri/${card_name}"
		fmtr::log "  -> dGPU DRM device: $drm_dgpu"
	else
		drm_igpu="/dev/dri/${card_name}"
		fmtr::log "  -> iGPU DRM device: $drm_igpu"
	fi
done

if [[ -z "$drm_dgpu" || -z "$drm_igpu" ]]; then
	fmtr::error "Could not detect both iGPU and dGPU DRM devices."
	fmtr::info "Make sure both GPUs are active (dGPU bound to amdgpu, not vfio-pci)."
	fmtr::info "Current dGPU driver: $(readlink "/sys/bus/pci/devices/${GPU_PCI_ADDR}/driver" 2>/dev/null | xargs basename 2>/dev/null || echo 'none')"
	exit 1
fi

# =============================================================================
# SECTION 4: Detect Monitors from Hyprland
# =============================================================================

fmtr::info "Detecting monitors from Hyprland..."
echo ""

# Parse monitors from hyprctl
monitor_json=$(hyprctl monitors -j 2>/dev/null)
monitor_count=$(echo "$monitor_json" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")

if ((monitor_count == 0)); then
	fmtr::error "No monitors detected from Hyprland."
	exit 1
fi

# Display monitors
echo "$monitor_json" | python3 -c "
import json, sys
monitors = json.load(sys.stdin)
for i, m in enumerate(monitors):
    print(f'  [{i+1}] {m[\"name\"]} - {m[\"width\"]}x{m[\"height\"]}@{m[\"refreshRate\"]:.0f}Hz - {m.get(\"description\",\"\")}')
"
echo ""

# Ask which monitor is iGPU
while :; do
	read -rp "$(fmtr::ask_inline 'Which monitor is connected to your iGPU/motherboard? (name, e.g. HDMI-A-4): ')" igpu_monitor
	if [[ -n "$igpu_monitor" ]]; then
		fmtr::log "iGPU monitor: $igpu_monitor"
		break
	fi
	fmtr::error "Monitor name cannot be empty."
done

# Ask which monitor is dGPU
while :; do
	read -rp "$(fmtr::ask_inline 'Which monitor is connected to your dGPU/graphics card? (name, e.g. DP-2): ')" dgpu_monitor
	if [[ -n "$dgpu_monitor" ]]; then
		fmtr::log "dGPU monitor: $dgpu_monitor"
		break
	fi
	fmtr::error "Monitor name cannot be empty."
done

# Refresh rates
read -rp "$(fmtr::ask_inline 'Refresh rate for iGPU monitor when gaming? (default 60): ')" igpu_hz_input
igpu_hz=${igpu_hz_input:-60}

read -rp "$(fmtr::ask_inline 'Refresh rate for dGPU monitor in Linux mode? (default 240): ')" dgpu_hz_input
dgpu_hz=${dgpu_hz_input:-240}

# Resolution
read -rp "$(fmtr::ask_inline 'Monitor resolution? (default 1920x1080): ')" resolution
resolution=${resolution:-1920x1080}

# =============================================================================
# SECTION 5: Detect UWSM Env File
# =============================================================================

fmtr::info "Detecting UWSM env file..."

uwsm_env=""
uwsm_candidates=(
	"$HOME/.config/uwsm/env-hyprland"
	"$HOME/.config/uwsm/env"
)

for candidate in "${uwsm_candidates[@]}"; do
	if [[ -f "$candidate" ]]; then
		if grep -q "WLR_DRM_DEVICES\|AQ_DRM_DEVICES" "$candidate" 2>/dev/null; then
			uwsm_env="$candidate"
			fmtr::log "Found UWSM env file with DRM vars: $uwsm_env"
			break
		fi
	fi
done

if [[ -z "$uwsm_env" ]]; then
	fmtr::warn "No UWSM env file with WLR_DRM_DEVICES/AQ_DRM_DEVICES found."
	fmtr::info "Candidates checked: ${uwsm_candidates[*]}"

	if prmt::yes_or_no "$(fmtr::ask "Create ${uwsm_candidates[0]} with DRM vars?")"; then
		mkdir -p "$(dirname "${uwsm_candidates[0]}")"
		touch "${uwsm_candidates[0]}"
		uwsm_env="${uwsm_candidates[0]}"
		fmtr::log "Created UWSM env file at $uwsm_env"
	else
		fmtr::error "UWSM env file required. Aborting."
		exit 1
	fi
fi

# Ensure DRM device vars exist
if ! grep -q "^export WLR_DRM_DEVICES=" "$uwsm_env" 2>/dev/null; then
	echo "export WLR_DRM_DEVICES=${drm_dgpu}" >>"$uwsm_env"
	fmtr::log "Added WLR_DRM_DEVICES=${drm_dgpu} to $uwsm_env"
else
	fmtr::log "WLR_DRM_DEVICES already exists in $uwsm_env"
fi

if ! grep -q "^export AQ_DRM_DEVICES=" "$uwsm_env" 2>/dev/null; then
	echo "export AQ_DRM_DEVICES=${drm_dgpu}" >>"$uwsm_env"
	fmtr::log "Added AQ_DRM_DEVICES=${drm_dgpu} to $uwsm_env"
else
	fmtr::log "AQ_DRM_DEVICES already exists in $uwsm_env"
fi

# =============================================================================
# SECTION 6: Detect Hyprland monitors.conf
# =============================================================================

fmtr::info "Detecting Hyprland monitors.conf..."

monitors_conf=""
monitors_candidates=(
	"$HOME/.config/hypr/edit_here/source/monitors.conf"
	"$HOME/.config/hypr/monitors.conf"
	"$HOME/.config/hypr/source/monitors.conf"
	"$HOME/.config/hypr/config/monitors.conf"
)

for candidate in "${monitors_candidates[@]}"; do
	if [[ -f "$candidate" ]]; then
		monitors_conf="$candidate"
		fmtr::log "Found monitors.conf: $monitors_conf"
		break
	fi
done

if [[ -z "$monitors_conf" ]]; then
	fmtr::warn "Could not auto-detect monitors.conf location."
	read -rp "$(fmtr::ask_inline 'Enter full path to your Hyprland monitors.conf: ')" monitors_conf
	if [[ ! -f "$monitors_conf" ]]; then
		fmtr::error "File not found: $monitors_conf"
		exit 1
	fi
fi

# =============================================================================
# SECTION 7: Detect VM Name
# =============================================================================

fmtr::info "Detecting VMs..."

vm_name="WindowsVM"
available_vms=$(virsh list --all --name 2>/dev/null | grep -v "^$")

if [[ -n "$available_vms" ]]; then
	vm_count=$(echo "$available_vms" | wc -l)
	if ((vm_count == 1)); then
		vm_name=$(echo "$available_vms" | head -1)
		fmtr::log "Found single VM: $vm_name (using as default)"
	else
		fmtr::info "Available VMs:"
		echo "$available_vms" | nl -w2 -s') '
		read -rp "$(fmtr::ask_inline "Enter VM name (default: WindowsVM): ")" vm_input
		vm_name=${vm_input:-WindowsVM}
	fi
else
	fmtr::info "No VMs found. Using default: WindowsVM"
fi
fmtr::log "VM name: $vm_name"

# =============================================================================
# SECTION 8: Detect Terminal Emulator for Keybind
# =============================================================================

terminal="kitty"
for term in kitty alacritty foot ghostty wezterm; do
	if command -v "$term" &>/dev/null; then
		terminal="$term"
		break
	fi
done
fmtr::log "Terminal emulator: $terminal"

# =============================================================================
# SECTION 9: Write gaming-mode.conf
# =============================================================================

fmtr::info "Writing gaming-mode.conf..."

cat >"${SCRIPT_DIR}/gaming-mode.conf" <<EOF
# Gaming Mode Configuration
# Generated by gaming-mode-setup.sh on $(date)
# Re-run gaming-mode-setup.sh to reconfigure

# User
GM_USER="${USER}"

# VM
GM_VM_NAME="${vm_name}"

# GPU PCI addresses (from config.conf)
GM_GPU_PCI="${GPU_PCI_ADDR}"
GM_GPU_AUDIO_PCI="${gpu_audio_pci}"
GM_GPU_ORIGINAL_DRIVER="${GPU_DRIVER_ORIGINAL:-amdgpu}"
GM_GPU_AUDIO_ORIGINAL_DRIVER="${gpu_audio_original_driver}"

# DRM devices (detected by PCI ID)
GM_DRM_DGPU="${drm_dgpu}"
GM_DRM_IGPU="${drm_igpu}"

# Monitor names (from hyprctl monitors)
GM_MONITOR_DGPU="${dgpu_monitor}"
GM_MONITOR_IGPU="${igpu_monitor}"

# Resolution and refresh rates
GM_RESOLUTION="${resolution}"
GM_HZ_DGPU="${dgpu_hz}"
GM_HZ_IGPU="${igpu_hz}"

# Config file paths
GM_UWSM_ENV="${uwsm_env}"
GM_MONITORS_CONF="${monitors_conf}"
EOF

fmtr::log "Configuration saved to: ${SCRIPT_DIR}/gaming-mode.conf"

# =============================================================================
# SECTION 10: Keybind Setup
# =============================================================================

keybind_file=""
keybind_candidates=(
	"$HOME/.config/hypr/edit_here/source/keybinds.conf"
	"$HOME/.config/hypr/keybinds.conf"
	"$HOME/.config/hypr/bindings.conf"
	"$HOME/.config/hypr/binds.conf"
	"$HOME/.config/hypr/edit_here/keybinds.conf"
)

for candidate in "${keybind_candidates[@]}"; do
	if [[ -f "$candidate" ]]; then
		keybind_file="$candidate"
		break
	fi
done

has_gaming_bind=false
if [[ -n "$keybind_file" ]]; then
	if grep -q "gaming-mode" "$keybind_file" 2>/dev/null; then
		has_gaming_bind=true
		fmtr::log "Gaming mode keybind already exists in $keybind_file"
	fi
fi

if [[ "$has_gaming_bind" == false && -n "$keybind_file" ]]; then
	fmtr::info "No gaming mode keybind found."
	if prmt::yes_or_no "$(fmtr::ask 'Add Super+G keybind to open gaming-mode.sh?')"; then
		echo "" >>"$keybind_file"
		echo "# Gaming Mode" >>"$keybind_file"
		echo "bind = SUPER, G, exec, $terminal --title \"Gaming Mode\" bash -c \"cd ${SCRIPT_DIR} && ./gaming-mode.sh\"" >>"$keybind_file"
		fmtr::log "Added Super+G keybind using $terminal to $keybind_file"
		hyprctl reload 2>/dev/null || true
	fi
fi

# =============================================================================
# SECTION 11: Install Systemd Service
# =============================================================================

fmtr::info "Installing gaming-mode-daemon systemd service..."
mkdir -p "$HOME/.config/systemd/user"

cat >"$HOME/.config/systemd/user/gaming-mode-daemon.service" <<EOF
[Unit]
Description=Gaming Mode Daemon
After=default.target

[Service]
Type=simple
ExecStart=${SCRIPT_DIR}/gaming-mode-daemon.sh
Restart=on-failure
RestartSec=5
StandardOutput=append:/tmp/gaming-mode/log
StandardError=append:/tmp/gaming-mode/log

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable gaming-mode-daemon.service
systemctl --user restart gaming-mode-daemon.service

if systemctl --user is-active gaming-mode-daemon.service &>/dev/null; then
	fmtr::log "Gaming mode daemon: RUNNING"
else
	fmtr::warn "Gaming mode daemon: FAILED TO START"
	fmtr::info "Check: systemctl --user status gaming-mode-daemon.service"
fi

# =============================================================================
# SECTION 12: Summary
# =============================================================================

echo ""
fmtr::box_text " Configuration Summary "
echo ""
cat "${SCRIPT_DIR}/gaming-mode.conf"
echo ""
fmtr::log "Setup complete!"
echo ""
fmtr::info "Next steps:"
fmtr::info "  1. Run ./gaming-mode.sh (or press Super+G)"
fmtr::info "  2. Select 'Start Gaming Mode'"
fmtr::info "  3. Hyprland will restart on iGPU - switch monitor to HDMI"
fmtr::info "  4. Confirm the screen looks correct"
fmtr::info "  5. Windows VM starts automatically"
fmtr::info "  6. Switch monitor to dGPU output to play"
echo ""
fmtr::info "To reconfigure, run: ./gaming-mode-setup.sh"
